# debug 开关
debug: true

# 项目的名字
project.name:  "kotlin_spider"

# 服务器的一些配置
server:
       address: 0.0.0.0
       port: 3000

# 数据库的设置
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/kotlin_spider?characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: 25802580
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.database: MYSQL
spring.data.jpa.repositories.enabled: true

# 只是喜欢彩色的 ...
spring.output.ansi.enabled: always